### ISSUE TITLE
error importing library using require in Node.js

### ISSUE THREAD

**Issue by davelandry** [superleap/github-issues-label-sync#42]
**What is the current behavior?**
Importing using this code:
```js
var LabelSync = require("github-issues-label-sync");
```

Produces this error:
```sh
Error: Cannot find module 'github-issues-label-sync'
```

**What is the expected behavior?**
This code worked in v1.18.0 😬

**Comment by vrtxf** [comment]
Sorry about this, was testing locally with npm link rather than using the gulp task (which was set to run on prepublish). I adjusted this issue but it will take 10-20more mins to get everything online !

**Comment by davelandry** [comment]
No worries, I totally get it. Thanks again!

**Comment by davelandry** [comment]
Still getting the same error after upgrading to v1.20.0 😞

**Comment by vrtxf** [comment]
v1.22.0 is what you need, sorry for the delay !
